### ISSUE TITLE
Finding the zeropod status of a pod 

### ISSUE THREAD

**Issue by mms-gianni** [ctrox/zeropod#15]
Hey there 

Congratulations on your talk yesterday at KCDZ. Was definitely my highlight!

I've tested it today and everything works fine. A really great project, which should get more attention (and probably will).

I was wondering if there is a simple way to see the zeropod status of a pod but I couldn't find one. 

My preferred way would be an additional annotation. 
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containerd.runc.v2.group: zeropod
    zeropod.ctrox.dev/cpu-requests: '{"nginx":"100m"}'
    zeropod.ctrox.dev/memory-requests: '{"nginx":"128Mi"}'
    zeropod.ctrox.dev/scaledown-duration: 10s
    zeropod.ctrox.dev/status: awake    <-------------------------------- awake | sleeping
  creationTimestamp: "2024-06-14T16:00:46Z"
```

**Comment by ctrox** [comment]
Thanks for the kind words and checking it out!

You are right, this is currently only visible via metrics. This is very similar to #5. Only very recently I added a little event system to the shim, that the zeropod-node manager can connect to (just another TTRPC socket that the shim creates) and then it will get [container status events](https://github.com/ctrox/zeropod/blob/main/api/shim/v1/shim.proto#L36) so that makes this very possible. I did not want to call out to the k8s API directly from the shim as that feels like bad separation of concerns.

Anyways, since a pod can have multiple containers, that would also need to be reflected somehow since you can have two containers in a pod with different states. So either the container name needs to be part of the annotation key or simple key-value pairs in the value as that would allow for a static key. Not too sure about using more json in the annotation values, I did this for storing the initial resource requests but that is not really meant to be "user-facing".

```yaml
zeropod.ctrox.dev/status/foo: running
zeropod.ctrox.dev/status/bar: scaled_down
# or
zeropod.ctrox.dev/status: foo=running,bar=scaled_down
````

**Comment by mms-gianni** [comment]
#5 seems to be the same issue. Sorry 😄 

Yes, you're right. I missed the multiple containers case. 

Both variants are looking valid to me. I haven't a specific preference there. 

`zeropod.ctrox.dev/status/foo: running` would be easier accessible or even queriable with :
```
kubectl get pod -A -o jsonpath='{.items[?(@.metadata.annotations.zeropod\.ctrox\.dev/status/foo=="running")].metadata.name}'
```

Or follow the cpu-requests/memory schema to bring in a third option. 

```
zeropod.ctrox.dev/memory-requests: '{"nginx":"scaled_down", "foo": "running"}'
```

**Comment by ctrox** [comment]
So I started working on this and I have these **labels** now:

```yaml
labels:
  status.zeropod.ctrox.dev/container1: RUNNING
  status.zeropod.ctrox.dev/container2: SCALED_DOWN
```

I like the `status.` prefix a bit more than having two slashes. The values are all caps because this is just the string representation of the RPC definitions, this makes it nice to use if someone were to interact with these labels from Go code. 

I have used labels instead of annotations because it's a bit more integrated in tooling, e.g. you can something like `kubectl get pods -l status.zeropod.ctrox.dev/container1=RUNNING` to get all pods which have a running `container1`. As these are labels you could even do stuff like have a service which only selects running containers. Your jsonpath query should also still work.

What do you think?
