### ISSUE TITLE
Insufficient Permissions to Create eBPF Directory on k3s

### ISSUE THREAD

**Issue by gentoorax** [ctrox/zeropod#49]
When deploying ZeroPod on k3s using your provided manifests (kubectl apply -k https://github.com/ctrox/zeropod/config/k3s), I'm getting a permission error on ghcr.io/ctrox/zeropod-manager:v0.6.1:

```
mkdir /sys/fs/bpf/zeropod_maps: permission denied
```

This happens because the container needs extra Linux capabilities/permissions (CAP_BPF, possibly CAP_SYS_ADMIN) to access eBPF.

Could you update the deployment to include the necessary security context maybe?

Might be due to the recent changes regarding rootless containers in k3s. For the record I'm using: v1.31.3+k3s1

**Comment by ctrox** [comment]
What is your host OS? I have not been able to reproduce this on fedora.

The cap SYS_ADMIN should already be there, can you try adding the bpf one to the zeropod-node daemonset (manager container) to see what is required on your system?

**Comment by gentoorax** [comment]
Apologies, had a lot on this week. Yes Ubuntu Minimal 22.04.4 LTS and K3S 1.31.3. I'll give this a go tomorrow, and report back. Thanks for getting back to me.

**Comment by gentoorax** [comment]
That seems to have caused the daemon set to start running. However, when deploying the test nginx pod from the documentation with the zeropod runtime, I don't see it scaling down, looks like it's just running with 1/1 Ready.

According to the manager...

```
{"time":"2025-04-10T22:36:33.221933491Z","level":"INFO","msg":"status event","component":"podlabeller","container":"nginx","pod":"nginx","namespace":"default","phase":1}
{"time":"2025-04-10T22:36:33.238613569Z","level":"INFO","msg":"updating pod resources using resize failed, falling back to update","sock":"/run/zeropod/s/a72dafdfb003c16f9efac097c47c22f44a0e8eb6d95b6ea90aacbc3b5a45fd6a.sock"}
```

**Comment by ctrox** [comment]
I found another issue that is unique to k3s, for some reason the `tar` binary available within the runtime environment is a busybox tar and not the full GNU tar. This broke criu checkpointing as it needs GNU tar. This and also the original issue described here should be fixed with the just released [v0.6.2](https://github.com/ctrox/zeropod/releases/tag/v0.6.2). This has also shown me that I should probably have a k3s specific e2e test as it should be quite simple to spin up in a CI action.

When it scales down, you should see the label `status.zeropod.ctrox.dev/nginx=SCALED_DOWN` on the pod. You should also see a status event in the log of the manager showing the phase change to: `"phase":0`.

**Comment by gentoorax** [comment]
Yeah sounds like a good idea.

I've updated to the latest. I don't seem to get those errors in the logs but my pod still seems to be running at 1/1. I was also wondering you apply zeropod to a deployment, I expected I'd just add the annotations to the deployment but they aren't applied and it's not picked up by the manager like the standalone pod is. Might be good to add an example of a deployment if that's possible as that is what most people will be using pods tend to just be applied standalone for the odd test.

Perhaps I just need to wait longer, I used the exact example provided in the readme, so didn't apply any timescales.
```
{"time":"2025-04-13T15:51:51.985867371Z","level":"INFO","msg":"subscribing to status events","sock":"/run/zeropod/s/77f7192421955145e9dedbaf086b6104fe29ff7d398f3f797567c5f648fb4b60.sock"}
{"time":"2025-04-13T15:51:52.899013191Z","level":"INFO","msg":"status event","component":"podlabeller","container":"nginx","pod":"nginx","namespace":"default","phase":1}
{"time":"2025-04-13T15:51:52.90151755Z","level":"INFO","msg":"attaching redirector for sandbox","pid":150281,"links":["eth0","lo"]}
{"time":"2025-04-13T15:52:53.105296299Z","level":"INFO","msg":"status event","component":"podlabeller","container":"nginx","pod":"nginx","namespace":"default","phase":0}
{"time":"2025-04-13T16:00:05.460918477Z","level":"INFO","msg":"status event","component":"podlabeller","container":"nginx","pod":"nginx","namespace":"default","phase":1}
```

I tried the following for a full deployment, but it didn't seem to be detected...
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        io.containerd.runc.v2.group: "zeropod"
        zeropod.ctrox.dev/scaledown-duration: 10s
    spec:
      runtimeClassName: zeropod
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
```
