### ISSUE TITLE
Live-migration: migration servers unset

### ISSUE THREAD

**Issue by eobrienvtech** [ctrox/zeropod#67]
I am trying to replicate the live-migration demo from this [Tech Talk](https://www.youtube.com/watch?v=yJtQfoftwJE&ab_channel=NineInternetSolutionsAG) using the freezer application in a KinD cluster.
OS: Ubuntu 24.04.2 LTS

When the pod is migrated to a new node the context is not maintained. A migration object is created on the source node (k8s-playground-worker2) but fails with the error message "migration servers unset" in the logs of the zeropod-node pod. 
I notice in the logs of the zeropod-system controller on the two worker nodes there is a message "live_migration_supported":false during deployment, but in the controller on the control-plane the message is "live_migration_supported":true. 

**Is there a specific configuration or flag that needs to be enabled on the worker nodes to support live migration?**

Logs of the zeropod-node pod on the source node:
```
$ kubectl logs zeropod-node-pz6lk -n zeropod-system
Defaulted container "manager" out of: manager, installer (init), prepare-bpf-fs (init)
{"time":"2025-06-12T11:29:47.708237342Z","level":"INFO","msg":"starting manager","metrics-addr":":8080"}
{"time":"2025-06-12T11:29:47.708531988Z","level":"INFO","msg":"maps path not found, creating","path":"/sys/fs/bpf/zeropod_maps"}
{"time":"2025-06-12T11:29:47.70859815Z","level":"INFO","msg":"no sandbox pids found"}
{"time":"2025-06-12T11:29:48.03443233Z","level":"INFO","msg":"init","component":"podlabeller"}
{"time":"2025-06-12T11:29:48.474046486Z","level":"INFO","msg":"new node server","name":"k8s-playground-worker2","live_migration_supported":false}
{"time":"2025-06-12T11:29:48.474184313Z","level":"INFO","msg":"starting node server","unix":{"Name":"/run/zeropod/node.sock","Net":"unix"},"socket":{"IP":"::","Port":8090,"Zone":""}}
{"time":"2025-06-12T11:29:48.474355873Z","level":"INFO","msg":"Starting EventSource","controller":"pod-controller","source":"kind source: *v1.Pod"}
{"time":"2025-06-12T11:29:48.583997869Z","level":"INFO","msg":"Starting Controller","controller":"pod-controller"}
{"time":"2025-06-12T11:29:48.584044818Z","level":"INFO","msg":"Starting workers","controller":"pod-controller","worker count":1}
.................
{"time":"2025-06-17T09:57:38.550223184Z","level":"INFO","msg":"got restore request","pod_name":"freezer-78c778cd99-m6g5h","pod_namespace":"default","container_name":"freezer"}
{"time":"2025-06-17T09:57:38.607946961Z","level":"INFO","msg":"claimed migration","name":"freezer-78c778cd99-66d4n","namespace":"default"}
{"time":"2025-06-17T09:57:48.746200847Z","level":"ERROR","msg":"migration servers unset","container_name":"freezer"}
{"time":"2025-06-17T09:57:48.789360366Z","level":"INFO","msg":"got finish restore request","pod_name":"freezer-78c778cd99-m6g5h","pod_namespace":"default","container_name":"freezer"}
{"time":"2025-06-17T10:39:11.100992176Z","level":"INFO","msg":"got evac preparation request","pod_name":"freezer-78c778cd99-m6g5h","pod_namespace":"default","container_name":"freezer"}
{"time":"2025-06-17T10:39:11.279209691Z","level":"INFO","msg":"created migration for pod","req":{"Namespace":"default","Name":"freezer-78c778cd99-m6g5h"},"pod_name":"freezer-78c778cd99-m6g5h","pod_namespace":"default"}
{"time":"2025-06-17T10:39:16.771374095Z","level":"INFO","msg":"migration is claimed"}
{"time":"2025-06-17T10:39:16.771395533Z","level":"INFO","msg":"evac prepare done"}
```

I have confirmed that CONFIG_USERFAULTFD is enabled
```bash
$ grep CONFIG_USERFAULTFD /boot/config-$(uname -r)
CONFIG_USERFAULTFD=y
```

```bash
$ kubectl get nodes --show-labels
NAME                           STATUS   ROLES           AGE     VERSION   LABELS
k8s-playground-control-plane   Ready    control-plane   4d23h   v1.33.1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-playground-control-plane,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=,zeropod.ctrox.dev/node=true
k8s-playground-worker          Ready    <none>          4d23h   v1.33.1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-playground-worker,kubernetes.io/os=linux,zeropod.ctrox.dev/node=true
k8s-playground-worker2         Ready    <none>          4d23h   v1.33.1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=k8s-playground-worker2,kubernetes.io/os=linux,zeropod.ctrox.dev/node=true
```

```
$ kubectl describe migration freezer-78c778cd99-m6g5h
Name:         freezer-78c778cd99-m6g5h
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  runtime.zeropod.ctrox.dev/v1
Kind:         Migration
Metadata:
  Creation Timestamp:  2025-06-17T10:39:11Z
  Generation:          2
  Resource Version:    690291
  UID:                 6bd680f9-de99-44c8-9962-7d3ab67972c1
Spec:
  Containers:
    Id:               f606ec6649e8a0f88979497f8b6fabe116a2366ecafcd06bd2aa90a866c07718
    Name:             freezer
  Live Migration:     false
  Pod Template Hash:  78c778cd99
  Source Node:        k8s-playground-worker2
  Source Pod:         freezer-78c778cd99-m6g5h
  Target Node:        k8s-playground-worker
  Target Pod:         freezer-78c778cd99-8jw4b
Status:
  Containers:
    Condition:
      Phase:             Failed
    Migration Duration:  0s
    Name:                freezer
Events:                  <none>
```

Contents of the file to deploy the freezer Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freezer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freezer
  template:
    metadata:
      labels:
        app: freezer
      annotations:
        zeropod.ctrox.dev/scaledown-duration: 10m
        zeropod.ctrox.dev/live-migrate: "freezer"
    spec:
      runtimeClassName: zeropod
      containers:
        - image: ghcr.io/ctrox/zeropod-freezer:latest
          name: freezer
          args: ["-memory", "128"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

---

apiVersion: v1
kind: Service
metadata:
  name: freezer
  labels:
    app: freezer
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
  selector:
    app: freezer
```
